# Generated by Django 4.1.13 on 2024-05-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlassesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
                ('sku', models.CharField(default='Unknown', max_length=100)),
            ],
            options={
                'db_table': 'MyApp_AR_glassesmodel',
            },
        ),
    ]
